export const menuData = {
    All: [
        { id: 1, name: "Cold Coffee", price: 30, quantity: 0 },
        { id: 2, name: "Thick Cold Coffee", price: 40, quantity: 0 },
        { id: 3, name: "Cold Coffee With Ice-Cream", price: 40, quantity: 0 },
        { id: 4, name: "Thick Cold Coffee with Choco Crush", price: 50, quantity: 0 },
        { id: 5, name: "Thick Cold Coffee with Ice Cream", price: 60, quantity: 0 },
        { id: 6, name: "Cad-B", price: 70, quantity: 0 },
        { id: 7, name: "White Cuca", price: 50, quantity: 0 },
        { id: 8, name: "White Cuca With Choco Crush", price: 60, quantity: 0 },
        { id: 9, name: "Kitkat Shake", price: 60, quantity: 0 },
        { id: 10, name: "Oreo Shake", price: 60, quantity: 0 },
        { id: 11, name: "5 Star Shake", price: 60, quantity: 0 },
        { id: 12, name: "Vanilla Ice-Cream", price: 30, quantity: 0 },
        { id: 13, name: "Chocolate Ice-Cream", price: 40, quantity: 0 },
        { id: 14, name: "Kesar Thandai", price: 60, quantity: 0 },
        { id: 15, name: "Kesar Badam Shake", price: 60, quantity: 0 },
        { id: 16, name: "Rose MilkShake", price: 60, quantity: 0 },
        { id: 17, name: "Strawberry MilkShake", price: 60, quantity: 0 },
        { id: 18, name: "Butterscotch MilkShake", price: 60, quantity: 0 },
        { id: 19, name: "Black Current MilkShake", price: 60, quantity: 0 },
        { id: 20, name: "Aniir MilkShake", price: 60, quantity: 0 },
        { id: 21, name: "Chocolate Badam MilkShake", price: 70, quantity: 0 },
        { id: 22, name: "French Fries", price: 70, quantity: 0 },
        { id: 23, name: "Peri Peri French Fries", price: 80, quantity: 0 },
        { id: 24, name: "Cheese French Fries", price: 100, quantity: 0 },
        { id: 25, name: "Hot Expresso Coffee", price: 25, quantity: 0 },
        { id: 26, name: "Hot Chocolate", price: 25, quantity: 0 },
        { id: 27, name: "Club Sandwich", price: 60, quantity: 0 },
        { id: 28, name: "Jain Sandwich", price: 60, quantity: 0 },
        { id: 29, name: "Potato Cheese Sandwich", price: 60, quantity: 0 },
        { id: 30, name: "Plain Cheese Sandwich", price: 60, quantity: 0 },
        { id: 31, name: "Chocolate Sandwich", price: 60, quantity: 0 },
        { id: 32, name: "Mayonnaise Veg Sandwich", price: 70, quantity: 0 },
        { id: 33, name: "Club Cheese Sandwich", price: 70, quantity: 0 },
        { id: 34, name: "Veg Cheese Sandwich", price: 70, quantity: 0 },
        { id: 35, name: "Bombay Grill", price: 70, quantity: 0 },
        { id: 36, name: "Jain Grill", price: 70, quantity: 0 },
        { id: 37, name: "Potato Cheese Grill", price: 70, quantity: 0 },
        { id: 38, name: "Club Cheese Grill", price: 70, quantity: 0 },
        { id: 39, name: "Onion Capsicum Cheese Grill", price: 70, quantity: 0 },
        { id: 40, name: "Schezwan Cheese Grill", price: 70, quantity: 0 },
        { id: 41, name: "Corn Cheese Grill Sandwich", price: 80, quantity: 0 },
        { id: 42, name: "Paneer Cheese Grill Sandwich", price: 90, quantity: 0 },
        { id: 43, name: "Veg Steam Momos", price: 60, quantity: 0 },
        { id: 44, name: "Fried Momos", price: 70, quantity: 0 },
        { id: 45, name: "Peri Peri Momos", price: 80, quantity: 0 },
        { id: 46, name: "Peri Peri Cheese Momos", price: 90, quantity: 0 },
        { id: 47, name: "Paneer Steam Momos", price: 80, quantity: 0 },
        { id: 48, name: "Paneer Fried Momos", price: 90, quantity: 0 },
        { id: 49, name: "Cheese Corn Steam Momos", price: 80, quantity: 0 },
        { id: 50, name: "Cheese Corn Fried Momos", price: 90, quantity: 0 },
        { id: 51, name: "Paneer Peri Peri Momos", price: 100, quantity: 0 },
        { id: 52, name: "Paneer Cheese Momos", price: 120, quantity: 0 },
        { id: 53, name: "Kur Kure Momos", price: 120, quantity: 0 },
        { id: 54, name: "Mojito Mint", price: 60, quantity: 0 },
        { id: 55, name: "Blue Lagoon", price: 60, quantity: 0 },
        { id: 56, name: "Pina Colada", price: 60, quantity: 0 },
        { id: 57, name: "Watermelon", price: 60, quantity: 0 },
        { id: 58, name: "Peach Ice Tea", price: 60, quantity: 0 },
        { id: 59, name: "Lemon Ice Tea", price: 60, quantity: 0 },
    ],
    Beverages: [
        { id: 1, name: "Cold Coffee", price: 30, quantity: 0 },
        { id: 2, name: "Thick Cold Coffee", price: 40, quantity: 0 },
        { id: 3, name: "Cold Coffee With Ice-Cream", price: 40, quantity: 0 },
        { id: 4, name: "Thick Cold Coffee with Choco Crush", price: 50, quantity: 0 },
        { id: 5, name: "Thick Cold Coffee with Ice Cream", price: 60, quantity: 0 },
        { id: 6, name: "Cad-B", price: 70, quantity: 0 },
        { id: 7, name: "White Cuca", price: 50, quantity: 0 },
        { id: 8, name: "White Cuca With Choco Crush", price: 60, quantity: 0 },
        { id: 9, name: "Kitkat Shake", price: 60, quantity: 0 },
        { id: 10, name: "Oreo Shake", price: 60, quantity: 0 },
        { id: 11, name: "5 Star Shake", price: 60, quantity: 0 },
        { id: 12, name: "Vanilla Ice-Cream", price: 30, quantity: 0 },
        { id: 13, name: "Chocolate Ice-Cream", price: 40, quantity: 0 },
        { id: 14, name: "Kesar Thandai", price: 60, quantity: 0 },
        { id: 15, name: "Kesar Badam Shake", price: 60, quantity: 0 },
        { id: 16, name: "Rose MilkShake", price: 60, quantity: 0 },
        { id: 17, name: "Strawberry MilkShake", price: 60, quantity: 0 },
        { id: 18, name: "Butterscotch MilkShake", price: 60, quantity: 0 },
        { id: 19, name: "Black Current MilkShake", price: 60, quantity: 0 },
        { id: 20, name: "Aniir MilkShake", price: 60, quantity: 0 },
        { id: 21, name: "Chocolate Badam MilkShake", price: 70, quantity: 0 },
      ],
    
      Fries: [
        { id: 22, name: "French Fries", price: 70, quantity: 0 },
        { id: 23, name: "Peri Peri French Fries", price: 80, quantity: 0 },
        { id: 24, name: "Cheese French Fries", price: 100, quantity: 0 },
      ],
    
      Hot: [
        { id: 25, name: "Hot Expresso Coffee", price: 25, quantity: 0 },
        { id: 26, name: "Hot Chocolate", price: 25, quantity: 0 },
      ],
    
      Sandwich: [
        { id: 27, name: "Club Sandwich", price: 60, quantity: 0 },
        { id: 28, name: "Jain Sandwich", price: 60, quantity: 0 },
        { id: 29, name: "Potato Cheese Sandwich", price: 60, quantity: 0 },
        { id: 30, name: "Plain Cheese Sandwich", price: 60, quantity: 0 },
        { id: 31, name: "Chocolate Sandwich", price: 60, quantity: 0 },
        { id: 32, name: "Mayonnaise Veg Sandwich", price: 70, quantity: 0 },
        { id: 33, name: "Club Cheese Sandwich", price: 70, quantity: 0 },
        { id: 34, name: "Veg Cheese Sandwich", price: 70, quantity: 0 },
        { id: 35, name: "Bombay Grill", price: 70, quantity: 0 },
        { id: 36, name: "Jain Grill", price: 70, quantity: 0 },
        { id: 37, name: "Potato Cheese Grill", price: 70, quantity: 0 },
        { id: 38, name: "Club Cheese Grill", price: 70, quantity: 0 },
        { id: 39, name: "Onion Capsicum Cheese Grill", price: 70, quantity: 0 },
        { id: 40, name: "Schezwan Cheese Grill", price: 70, quantity: 0 },
        { id: 41, name: "Corn Cheese Grill Sandwich", price: 80, quantity: 0 },
        { id: 42, name: "Paneer Cheese Grill Sandwich", price: 90, quantity: 0 },
      ],
    
      Momos: [
        { id: 43, name: "Veg Steam Momos", price: 60, quantity: 0 },
        { id: 44, name: "Fried Momos", price: 70, quantity: 0 },
        { id: 45, name: "Peri Peri Momos", price: 80, quantity: 0 },
        { id: 46, name: "Peri Peri Cheese Momos", price: 90, quantity: 0 },
        { id: 47, name: "Paneer Steam Momos", price: 80, quantity: 0 },
        { id: 48, name: "Paneer Fried Momos", price: 90, quantity: 0 },
        { id: 49, name: "Cheese Corn Steam Momos", price: 80, quantity: 0 },
        { id: 50, name: "Cheese Corn Fried Momos", price: 90, quantity: 0 },
        { id: 51, name: "Paneer Peri Peri Momos", price: 100, quantity: 0 },
        { id: 52, name: "Paneer Cheese Momos", price: 120, quantity: 0 },
        { id: 53, name: "Kur Kure Momos", price: 120, quantity: 0 },
      ],
    
      Mocktails: [
        { id: 54, name: "Mojito Mint", price: 60, quantity: 0 },
        { id: 55, name: "Blue Lagoon", price: 60, quantity: 0 },
        { id: 56, name: "Pina Colada", price: 60, quantity: 0 },
        { id: 57, name: "Watermelon", price: 60, quantity: 0 },
        { id: 58, name: "Peach Ice Tea", price: 60, quantity: 0 },
        { id: 59, name: "Lemon Ice Tea", price: 60, quantity: 0 },
      ]    

  }